### ISSUE TITLE
当前登录环境异常。为了你的帐号安全，暂时不能登录web微信。你可以通过手机客户端或者windows微信登录。

### ISSUE THREAD

**Issue by skyfister** [HanSon/vbot#201]
你好，getLogin()里面get redirect_uri的时候提示：“当前登录环境异常。为了你的帐号安全，暂时不能登录web微信。你可以通过手机客户端或者windows微信登录。”是什么原因，有办法解决吗？偶尔会遇到这种情况，错误日志如下：
[2017-07-31 00:29:19][INFO] please scan the qrCode with wechat.
[2017-07-31 00:29:19][INFO] https:\/\/login.weixin.qq.com\/cgi-bin\/mmwebwx-bin\/login?tip=1&uuid=Id_k2vtROQ==&_=1501432159
[2017-07-31 00:29:21][INFO] window.code=201;
[2017-07-31 00:29:21][INFO] please confirm login in wechat.
[2017-07-31 00:29:21][INFO] https:\/\/login.weixin.qq.com\/cgi-bin\/mmwebwx-bin\/login?tip=0&uuid=Id_k2vtROQ==&_=1501432161
[2017-07-31 00:29:27][INFO] window.code=200;
window.redirect_uri=\"https:\/\/wx.qq.com\/cgi-bin\/mmwebwx-bin\/webwxnewloginpage?ticket=AeBCOtQE0tfm_ICxUg9mCA3g@qrticket_0&uuid=Id_k2vtROQ==&lang=zh_CN&scan=1501432161\";
[2017-07-31 00:29:27][INFO] <error><ret>1203<\/ret><message>当前登录环境异常。为了你的帐号安全，暂时不能登录web微信。你可以通过手机客户端或者windows微信登录。<\/message><\/error>
a:2:{s:5:\"errno\";i:105;s:6:\"errmsg\";s:31:\"Exception:Undefined index: skey\";}","stderr":"[2017-07-31 00:29:28] vbot.ERROR: Undefined index: skey [] []
PHP Fatal error:  Uncaught ErrorException: Undefined index: skey in \/var\/www\/grouphub\/vendor\/hanson\/vbot\/src\/Core\/Server.php:193
Stack trace:
#0 \/var\/www\/grouphub\/vendor\/hanson\/vbot\/src\/Core\/Server.php(193): Hanson\\Vbot\\Foundation\\ExceptionHandler->handleError(8, 'Undefined index...', '\/var\/www\/grouph...', 193, Array)
#1 \/var\/www\/grouphub\/vendor\/hanson\/vbot\/src\/Core\/Server.php(93): Hanson\\Vbot\\Core\\Server->getLogin()
#2 \/var\/www\/grouphub\/vendor\/hanson\/vbot\/src\/Core\/Server.php(35): Hanson\\Vbot\\Core\\Server->login()
#3 \/var\/www\/grouphub\/webwxbot.php(174): Hanson\\Vbot\\Core\\Server->serve()

**Comment by HanSon** [comment]
https://github.com/HanSon/vbot/issues/200 duplicate
