### ISSUE TITLE
扫码后报错 array_merge(): Argument #2 is not an array

### ISSUE THREAD

**Issue by phpfor** [HanSon/vbot#211]
[2017-08-25 10:40:14][INFO] init success.
[2017-08-25 10:40:14][自定义消息] 登录成功
[2017-08-25 10:40:14][INFO] init contacts begin.
[2017-08-25 10:40:18][自定义消息] 获取好友成功
[2017-08-25 10:40:18][自定义消息] 准备接收消息
PHP Fatal error:  Uncaught ErrorException: array_merge(): Argument #2 is not an array in /Library/WebServer/Documents/my-vbot/vendor/vbot/hot-girl/src/HotGirl.php:101
Stack trace:
#0 [internal function]: Hanson\Vbot\Foundation\ExceptionHandler->handleError(2, 'array_merge(): ...', '/Library/WebSer...', 101, Array)
#1 /Library/WebServer/Documents/my-vbot/vendor/vbot/hot-girl/src/HotGirl.php(101): array_merge(Array, NULL)
#2 /Library/WebServer/Documents/my-vbot/vendor/hanson/vbot/src/Extension/AbstractMessageHandler.php(41): Vbot\HotGirl\HotGirl->register()
#3 /Library/WebServer/Documents/my-vbot/vendor/hanson/vbot/src/Extension/MessageExtension.php(64): Hanson\Vbot\Extension\AbstractMessageHandler->init()
#4 /Library/WebServer/Documents/my-vbot/vendor/hanson/vbot/src/Core/MessageHandler.php(31): Hanson\Vbot\Extension\MessageExtension->initServiceExtensions()
#5 /Library/WebServer/Documents/my-vbot/vendor/hanson/vbot/src/Core/Server.php(43): Hanson\Vbot\Core\MessageHandler->listen()
#6 /Library/WebServer/Documents/my-vbot/Exampl in /Library/WebServer/Documents/my-vbot/vendor/vbot/hot-girl/src/HotGirl.php on line 101
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalErrorException: Uncaught ErrorException: array_merge(): Argument #2 is not an array in /Library/WebServer/Documents/my-vbot/vendor/vbot/hot-girl/src/HotGirl.php:101
Stack trace:
#0 [internal function]: Hanson\Vbot\Foundation\ExceptionHandler->handleError(2, 'array_merge(): ...', '/Library/WebSer...', 101, Array)
#1 /Library/WebServer/Documents/my-vbot/vendor/vbot/hot-girl/src/HotGirl.php(101): array_merge(Array, NULL)
#2 /Library/WebServer/Documents/my-vbot/vendor/hanson/vbot/src/Extension/AbstractMessageHandler.php(41): Vbot\HotGirl\HotGirl->register()
#3 /Library/WebServer/Documents/my-vbot/vendor/hanson/vbot/src/Extension/MessageExtension.php(64): Hanson\Vbot\Extension\AbstractMessageHandler->init()
#4 /Library/WebServer/Documents/my-vbot/vendor/hanson/vbot/src/Core/MessageHandler.php(31): Hanson\Vbot\Extension\MessageExtension->initServiceExtensions()
#5 /Library/WebServer/Documents/my-vbot/vendor/hanson/vbot/src/Core/Server.php(43): Hanson\Vbot\Core\Message in /Library/WebServer/Documents/my-vbot/vendor/vbot/hot-girl/src/HotGirl.php on line 101

**Comment by 466934322** [comment]
这个问题是因为config.php文件不完整造成的。

**Comment by 466934322** [comment]
具体的内容是什么我不知道，我的做法是在配置文件里面加了 一个 hot-girl=>[],的空数组

**Comment by phpfor** [comment]
还真是，配上 hot-girl=>[], 就好了。谢谢这位朋友！

**Comment by qiufeng5LIFE** [comment]
我在config.php文件中加了'hot-girl' => [],但是还是报这个错？是需要给个默认值吗？

**Comment by liuyangge** [comment]
我也加了'hot-girl' => [], 一样报错

**Comment by tao2581** [comment]
正确的配置名称：
> 'extension.hot_girl' => []

![image](https://user-images.githubusercontent.com/3303524/33795051-9c19b1be-dd13-11e7-8c4f-1b7c78bcc1c2.png)

**Comment by huanglike** [comment]
一楼是在linux下部署的吗？我的Windows下 cmd里扫码后输出的全是中文乱码头疼。

**Comment by huanglike** [comment]
肯定的呀，array_merge的参数必须都是数组，否则肯定给你警告啊。
