### ISSUE TITLE
PHP Fatal error:  Uncaught Hanson\Vbot\Exceptions\InitFailException: Init failed.

### ISSUE THREAD

**Issue by 466934322** [HanSon/vbot#215]
PHP Fatal error:  Uncaught Hanson\Vbot\Exceptions\InitFailException: Init failed. in /www/web/vboot/public_html/vot/my-vbot/vendor/hanson/vbot/src/Core/Server.php:245
Stack trace:
#0 [internal function]: Hanson\Vbot\Core\Server->Hanson\Vbot\Core\{closure}(Array, 0, Array, Array, Array, '', '', 0, 0, 0, 0, 0, Array, 0)
#1 /www/web/vboot/public_html/vot/my-vbot/vendor/hanson/vbot/src/Core/ApiExceptionHandler.php(18): call_user_func_array(Object(Closure), Array)
#2 /www/web/vboot/public_html/vot/my-vbot/vendor/hanson/vbot/src/Core/Server.php(246): Hanson\Vbot\Core\ApiExceptionHandler::handle(Array, Object(Closure))
#3 /www/web/vboot/public_html/vot/my-vbot/vendor/hanson/vbot/src/Core/Server.php(38): Hanson\Vbot\Core\Server->init()
#4 /www/web/vboot/public_html/vot/my-vbot/Example.php(50): Hanson\Vbot\Core\Server->serve()
#5 /www/web/vboot/public_html/vot/my-vbot/run.php(9): Hanson\MyVbot\Example->run()
#6 {main}
  thrown in /www/web/vboot/public_html/vot/my-vbot/vendor/hanson/vbot/src/Core/Server.php on line 245
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalErrorException: Uncaught Hanson\Vbot\Exceptions\InitFailException: Init failed. in /www/web/vboot/public_html/vot/my-vbot/vendor/hanson/vbot/src/Core/Server.php:245
Stack trace:
#0 [internal function]: Hanson\Vbot\Core\Server->Hanson\Vbot\Core\{closure}(Array, 0, Array, Array, Array, '', '', 0, 0, 0, 0, 0, Array, 0)
#1 /www/web/vboot/public_html/vot/my-vbot/vendor/hanson/vbot/src/Core/ApiExceptionHandler.php(18): call_user_func_array(Object(Closure), Array)
#2 /www/web/vboot/public_html/vot/my-vbot/vendor/hanson/vbot/src/Core/Server.php(246): Hanson\Vbot\Core\ApiExceptionHandler::handle(Array, Object(Closure))
#3 /www/web/vboot/public_html/vot/my-vbot/vendor/hanson/vbot/src/Core/Server.php(38): Hanson\Vbot\Core\Server->init()
#4 /www/web/vboot/public_html/vot/my-vbot/Example.php(50): Hanson\Vbot\Core\Server->serve()
#5 /www/web/vboot/public_html/vot/my-vbot/run.php(9): Hanson\MyVbot\Example->run()
#6 {main}
  thrown in /www/web/vboot/public_html/vot/my-vbot/vend in /www/web/vboot/public_html/vot/my-vbot/vendor/hanson/vbot/src/Core/Server.php on line 245

**Comment by 466934322** [comment]
this log is 
[2017-09-20 18:42:19] vbot.ERROR: Init failed.{"Ret":1101,"ErrMsg":""}

**Comment by 466934322** [comment]
logout

**Comment by 466934322** [comment]
这个问题是由于扫码过快导致的。出现二维码之后，等3s扫码，扫完后在等2s同意登录

**Comment by HanSon** [comment]
@466934322 其实不是，是某个值存在某些特殊符号就会出现，几率性，还没修复

**Comment by jasonzhouu** [comment]
遇到同样的问题

**Comment by qq99751336** [comment]
+1 , centos 7

**Comment by coolsky99** [comment]
这个问题还没有解决吗  扫了好多次码都不行

**Comment by ysnows** [comment]
手机上先退出再重新登录就可以了
