### ISSUE TITLE
扫码后报错，vbot.ERROR: Type error: Argument 2

### ISSUE THREAD

**Issue by vincent-anlan** [HanSon/vbot#234]
看了之前也有提出同样问题的，但是可能版本更新了,找不到hotgirl了，请问有没有遇到相同问题的？

`[2017-12-27 22:59:38] vbot.ERROR: Type error: Argument 2 passed to Illuminate\Redis\RedisManager::__construct() must be of the type array, null given, called in /root/vbot/vendor/hanson/vbot/src/Foundation/ServiceProviders/CacheServiceProvider.php on line 31 [] []
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 2 passed to Illuminate\Redis\RedisManager::__construct() must be of the type array, null given, called in /root/vbot/vendor/hanson/vbot/src/Foundation/ServiceProviders/CacheServiceProvider.php on line 31 in /root/vbot/vendor/illuminate/redis/RedisManager.php:40
Stack trace:
#0 /root/vbot/vendor/hanson/vbot/src/Foundation/ServiceProviders/CacheServiceProvider.php(31): Illuminate\Redis\RedisManager->__construct('predis', NULL)
#1 /root/vbot/vendor/illuminate/container/Container.php(749): Hanson\Vbot\Foundation\ServiceProviders\CacheServiceProvider->Hanson\Vbot\Foundation\ServiceProviders\{closure}(Object(Hanson\Vbot\Foundation\Vbot), Array)
#2 /root/vbot/vendor/illuminate/container/Container.php(631): Illuminate\Container\Container->build(Object(Closure))
#3 /root/vbot/vendor/illuminate/container/Container.php(586): Illuminate\Container\Container->resolve('redis', Array)
#4 /root/vbot/vendor/illuminate/container/Container.php(1 in /root/vbot/vendor/illuminate/redis/RedisManager.php on line 40
[2017-12-27 22:59:38] vbot.ERROR: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 2 passed to Illuminate\Redis\RedisManager::__construct() must be of the type array, null given, called in /root/vbot/vendor/hanson/vbot/src/Foundation/ServiceProviders/CacheServiceProvider.php on line 31 in /root/vbot/vendor/illuminate/redis/RedisManager.php:40 Stack trace: #0 /root/vbot/vendor/hanson/vbot/src/Foundation/ServiceProviders/CacheServiceProvider.php(31): Illuminate\Redis\RedisManager->__construct('predis', NULL) #1 /root/vbot/vendor/illuminate/container/Container.php(749): Hanson\Vbot\Foundation\ServiceProviders\CacheServiceProvider->Hanson\Vbot\Foundation\ServiceProviders\{closure}(Object(Hanson\Vbot\Foundation\Vbot), Array) #2 /root/vbot/vendor/illuminate/container/Container.php(631): Illuminate\Container\Container->build(Object(Closure)) #3 /root/vbot/vendor/illuminate/container/Container.php(586): Illuminate\Container\Container->resolve('redis', Array) #4 /root/vbot/vendor/illuminate/container/Container.php(1 [] []
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalErrorException: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 2 passed to Illuminate\Redis\RedisManager::__construct() must be of the type array, null given, called in /root/vbot/vendor/hanson/vbot/src/Foundation/ServiceProviders/CacheServiceProvider.php on line 31 in /root/vbot/vendor/illuminate/redis/RedisManager.php:40
Stack trace:
#0 /root/vbot/vendor/hanson/vbot/src/Foundation/ServiceProviders/CacheServiceProvider.php(31): Illuminate\Redis\RedisManager->__construct('predis', NULL)
#1 /root/vbot/vendor/illuminate/container/Container.php(749): Hanson\Vbot\Foundation\ServiceProviders\CacheServiceProvider->Hanson\Vbot\Foundation\ServiceProviders\{closure}(Object(Hanson\Vbot\Foundation\Vbot), Array)
#2 /root/vbot/vendor/illuminate/container/Container.php(631): Illuminate\Container\Container->build(Object(Closure))
#3 /root/vbot/vendor/illuminate/container/Container.php(586): Illuminate\Container\Container->resolve('redis',  in /root/vbot/vendor/illuminate/redis/RedisManager.php on line 40
`

**Comment by vincent-anlan** [comment]
不好意思 https://github.com/HanSon/vbot/issues/232 repost
