### ISSUE TITLE
composer下载、启动、手机扫描确认登录后，PHP报错停止运行

### ISSUE THREAD

**Issue by linxiaojialin** [Hanson/vbot#273]
swoole已开，redis已开

报错信息：
`PHP Fatal error:  Uncaught ErrorException: Undefined index: skey in /data/wwwroot/vbot/vendor/hanson/vbot/src/Core/Server.php:194
Stack trace:
#0 /data/wwwroot/vbot/vendor/hanson/vbot/src/Core/Server.php(194): Hanson\Vbot\Foundation\ExceptionHandler->handleError(8, 'Undefined index...', '/data/wwwroot/v...', 194, Array)
#1 /data/wwwroot/vbot/vendor/hanson/vbot/src/Core/Server.php(93): Hanson\Vbot\Core\Server->getLogin()
#2 /data/wwwroot/vbot/vendor/hanson/vbot/src/Core/Server.php(35): Hanson\Vbot\Core\Server->login()
#3 /data/wwwroot/vbot/run.php(74): Hanson\Vbot\Core\Server->serve()
#4 {main}
  thrown in /data/wwwroot/vbot/vendor/hanson/vbot/src/Core/Server.php on line 194
[2018-11-17 00:11:39] vbot.ERROR: Uncaught ErrorException: Undefined index: skey in /data/wwwroot/vbot/vendor/hanson/vbot/src/Core/Server.php:194 Stack trace: #0 /data/wwwroot/vbot/vendor/hanson/vbot/src/Core/Server.php(194): Hanson\Vbot\Foundation\ExceptionHandler->handleError(8, 'Undefined index...', '/data/wwwroot/v...', 194, Array) #1 /data/wwwroot/vbot/vendor/hanson/vbot/src/Core/Server.php(93): Hanson\Vbot\Core\Server->getLogin() #2 /data/wwwroot/vbot/vendor/hanson/vbot/src/Core/Server.php(35): Hanson\Vbot\Core\Server->login() #3 /data/wwwroot/vbot/run.php(74): Hanson\Vbot\Core\Server->serve() #4 {main}   thrown [] []
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalErrorException: Uncaught ErrorException: Undefined index: skey in /data/wwwroot/vbot/vendor/hanson/vbot/src/Core/Server.php:194
Stack trace:
#0 /data/wwwroot/vbot/vendor/hanson/vbot/src/Core/Server.php(194): Hanson\Vbot\Foundation\ExceptionHandler->handleError(8, 'Undefined index...', '/data/wwwroot/v...', 194, Array)
#1 /data/wwwroot/vbot/vendor/hanson/vbot/src/Core/Server.php(93): Hanson\Vbot\Core\Server->getLogin()
#2 /data/wwwroot/vbot/vendor/hanson/vbot/src/Core/Server.php(35): Hanson\Vbot\Core\Server->login()
#3 /data/wwwroot/vbot/run.php(74): Hanson\Vbot\Core\Server->serve()
#4 {main}
  thrown in /data/wwwroot/vbot/vendor/hanson/vbot/src/Core/Server.php:194
Stack trace:
#0 {main}
  thrown in /data/wwwroot/vbot/vendor/hanson/vbot/src/Core/Server.php on line 194`

**Comment by surpaimb** [comment]
你的微信号没有网页登录权限

**Comment by zhangrenjie** [comment]
新帐号吧？你去wx.qq.com登录一下就知道了

**Comment by jackwangshukai** [comment]
我是老的微信号也不行。感觉是不是在逐渐清理网页版
