### ISSUE TITLE
大佬们，我这怎么已扫码就报错啊

### ISSUE THREAD

**Issue by Chenilove** [Hanson/vbot#286]
已扫码就报错，我就是按照官网配置的 http://create.hanc.cc/vbot/docs/run.html
还有这sessionID怎么拿啊。。
vbot.ERROR: Too few arguments to function Illuminate\Redis\RedisManager::__construct(), 2 passed in /root/vbot/vendor/hanson/vbot/src/Foundation/ServiceProviders/CacheServiceProvider.php on line 31 and exactly 3 expected [] []
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Hanson\Vbot\Foundation\ExceptionHandler::report() must be an instance of Exception, instance of ArgumentCountError given, called in /root/vbot/vendor/hanson/vbot/src/Foundation/ExceptionHandler.php on line 133 and defined in /root/vbot/vendor/hanson/vbot/src/Foundation/ExceptionHandler.php:58
Stack trace:
#0 /root/vbot/vendor/hanson/vbot/src/Foundation/ExceptionHandler.php(133): Hanson\Vbot\Foundation\ExceptionHandler->report(Object(ArgumentCountError))
#1 [internal function]: Hanson\Vbot\Foundation\ExceptionHandler->handleException(Object(ArgumentCountError))
#2 {main}
  thrown in /root/vbot/vendor/hanson/vbot/src/Foundation/ExceptionHandler.php on line 58
PHP Fatal error:  Uncaught Error: Class 'Symfony\Component\Debug\Exception\FatalErrorException' not found in /root/vbot/vendor/hanson/vbot/src/Foundation/ExceptionHandler.php:180
Stack trace:
#0 /root/vbot/vendor/hanson/vbot/src/Foundation/ExceptionHandler.php(164): Hanson\Vbot\Foundation\ExceptionHandler->fatalExceptionFromError(Array, 0)
#1 [internal function]: Hanson\Vbot\Foundation\ExceptionHandler->handleShutdown()
#2 {main}
  thrown in /root/vbot/vendor/hanson/vbot/src/Foundation/ExceptionHandler.php on line 180
![1](https://user-images.githubusercontent.com/44698638/55554808-4892fb80-5716-11e9-8ee4-857724017476.png)

**Comment by Lichmaker** [comment]
session id是自动生成的，不是必填项。

你是在laravel中运行的吗？
`Too few arguments to function Illuminate\Redis\RedisManager::__construct()`
可以看出是版本问题导致的

**Comment by Lichmaker** [comment]
可以参考一下这个issues，一样的问题https://github.com/Hanson/vbot/issues/266

**Comment by legeng** [comment]
按照#266的改了代码也还是报错啊，laravel 5.8

**Comment by ld-wang** [comment]
PHP Fatal error: Uncaught Error: Class 'Symfony\Component\Debug\Exception\FatalErrorException'

缺少类文件, 需要安装symfony/debug
